# Site settings
title_left    : "Phu's "
title_right   : "Blog" # default: ""
description   : "Some Technical Writing on Machine Learning and Others"
keywords      : "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url           : https://phutoast.github.io # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-XXXXX-XX
twitter_username  : ""
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

collections:
  notes:
    output: true
    permalink: /:collection/:name

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Phu Sakulwongtana"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog
  - slug : papers
    title: Papers Notes

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
